# Nazwa aplikacji
spring.application.name=cinema-booking

# Konfiguracja polaczenia z baza PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/cinemadb
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1708}

# Sterownik PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialekt Hibernate dla PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate - automatyczne tworzenie/aktualizacja struktur tabel w bazie
spring.jpa.hibernate.ddl-auto=update

# Wy?wietlanie sformatowanych zapytan SQL w konsoli podczas dzialania aplikacji
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true